stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
      - src/data/data_collection.py
      - params.yaml
    params:
      - data_collection.test_size
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  data_preprocessing:
    cmd: python src/data/data_prepro.py
    deps:
      - src/data/data_prepro.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/processed/train_processed.csv
      - params.yaml
    params:
      - model_building.n_estimators
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python src/model/model_eval.py
    deps:
      - src/model/model_eval.py
      - models/model.pkl
      - data/processed/test_processed.csv
    metrics:
      - reports/metrics.json
    outs:
      - reports/run_info.json
      - reports/confusion_matrix_Best_Model.png

  model_registration:
    cmd: python src/model/model_reg.py
    deps:
      - src/model/model_reg.py
      - reports/run_info.json